/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AgcSoybeanProductionCostInputs {
    'socket': string;
  }
  interface AgcSoybeanProductionCostInputsAttributes extends StencilHTMLAttributes {
    'socket'?: string;
  }

  interface AgcSoybeanProductionCostProgress {
    'socket': string;
  }
  interface AgcSoybeanProductionCostProgressAttributes extends StencilHTMLAttributes {
    'socket'?: string;
  }

  interface AgcSoybeanProductionCostResultsPlaceholder {}
  interface AgcSoybeanProductionCostResultsPlaceholderAttributes extends StencilHTMLAttributes {}

  interface AgcSoybeanProductionCostResults {
    'socket': string;
  }
  interface AgcSoybeanProductionCostResultsAttributes extends StencilHTMLAttributes {
    'socket'?: string;
  }

  interface AgcSoybeanProductionCost {
    'mode': "full" | "step";
    'socket': string;
    'tract': string;
    'units': any;
  }
  interface AgcSoybeanProductionCostAttributes extends StencilHTMLAttributes {
    'mode'?: "full" | "step";
    'onAgcCalculated'?: (event: CustomEvent) => void;
    'onAgcStepChanged'?: (event: CustomEvent) => void;
    'socket'?: string;
    'tract'?: string;
    'units'?: any;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AgcSoybeanProductionCostInputs': Components.AgcSoybeanProductionCostInputs;
    'AgcSoybeanProductionCostProgress': Components.AgcSoybeanProductionCostProgress;
    'AgcSoybeanProductionCostResultsPlaceholder': Components.AgcSoybeanProductionCostResultsPlaceholder;
    'AgcSoybeanProductionCostResults': Components.AgcSoybeanProductionCostResults;
    'AgcSoybeanProductionCost': Components.AgcSoybeanProductionCost;
  }

  interface StencilIntrinsicElements {
    'agc-soybean-production-cost-inputs': Components.AgcSoybeanProductionCostInputsAttributes;
    'agc-soybean-production-cost-progress': Components.AgcSoybeanProductionCostProgressAttributes;
    'agc-soybean-production-cost-results-placeholder': Components.AgcSoybeanProductionCostResultsPlaceholderAttributes;
    'agc-soybean-production-cost-results': Components.AgcSoybeanProductionCostResultsAttributes;
    'agc-soybean-production-cost': Components.AgcSoybeanProductionCostAttributes;
  }


  interface HTMLAgcSoybeanProductionCostInputsElement extends Components.AgcSoybeanProductionCostInputs, HTMLStencilElement {}
  var HTMLAgcSoybeanProductionCostInputsElement: {
    prototype: HTMLAgcSoybeanProductionCostInputsElement;
    new (): HTMLAgcSoybeanProductionCostInputsElement;
  };

  interface HTMLAgcSoybeanProductionCostProgressElement extends Components.AgcSoybeanProductionCostProgress, HTMLStencilElement {}
  var HTMLAgcSoybeanProductionCostProgressElement: {
    prototype: HTMLAgcSoybeanProductionCostProgressElement;
    new (): HTMLAgcSoybeanProductionCostProgressElement;
  };

  interface HTMLAgcSoybeanProductionCostResultsPlaceholderElement extends Components.AgcSoybeanProductionCostResultsPlaceholder, HTMLStencilElement {}
  var HTMLAgcSoybeanProductionCostResultsPlaceholderElement: {
    prototype: HTMLAgcSoybeanProductionCostResultsPlaceholderElement;
    new (): HTMLAgcSoybeanProductionCostResultsPlaceholderElement;
  };

  interface HTMLAgcSoybeanProductionCostResultsElement extends Components.AgcSoybeanProductionCostResults, HTMLStencilElement {}
  var HTMLAgcSoybeanProductionCostResultsElement: {
    prototype: HTMLAgcSoybeanProductionCostResultsElement;
    new (): HTMLAgcSoybeanProductionCostResultsElement;
  };

  interface HTMLAgcSoybeanProductionCostElement extends Components.AgcSoybeanProductionCost, HTMLStencilElement {}
  var HTMLAgcSoybeanProductionCostElement: {
    prototype: HTMLAgcSoybeanProductionCostElement;
    new (): HTMLAgcSoybeanProductionCostElement;
  };

  interface HTMLElementTagNameMap {
    'agc-soybean-production-cost-inputs': HTMLAgcSoybeanProductionCostInputsElement
    'agc-soybean-production-cost-progress': HTMLAgcSoybeanProductionCostProgressElement
    'agc-soybean-production-cost-results-placeholder': HTMLAgcSoybeanProductionCostResultsPlaceholderElement
    'agc-soybean-production-cost-results': HTMLAgcSoybeanProductionCostResultsElement
    'agc-soybean-production-cost': HTMLAgcSoybeanProductionCostElement
  }

  interface ElementTagNameMap {
    'agc-soybean-production-cost-inputs': HTMLAgcSoybeanProductionCostInputsElement;
    'agc-soybean-production-cost-progress': HTMLAgcSoybeanProductionCostProgressElement;
    'agc-soybean-production-cost-results-placeholder': HTMLAgcSoybeanProductionCostResultsPlaceholderElement;
    'agc-soybean-production-cost-results': HTMLAgcSoybeanProductionCostResultsElement;
    'agc-soybean-production-cost': HTMLAgcSoybeanProductionCostElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
